name: Test Debezium UI Frontend

on:
  push:
    branches:
      - smokeWithCypress
  pull_request:
    branches:
      - smokeWithCypress
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBEZIUM_VERSION: "v1.5.0.Beta1"
    steps:
      - name: Checkout Debezium main repository
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium
          ref: ${{ env.DEBEZIUM_VERSION }}
          path: debezium    

      - name: Checkout Debezium UI
        uses: actions/checkout@v2
        with:
          repository: uidoyen/debtest
          path: dbzui

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: dbzui-${{ runner.os }}-maven-${{ hashFiles('dbzui/pom.xml', 'dbzui/**/pom.xml') }}
          restore-keys: |
            dbzui-${{ runner.os }}-maven-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache local Yarn repository
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: dbzui-${{ runner.os }}-yarn-${{ hashFiles('dbzui/ui/yarn.lock') }}
          restore-keys: |
            dbzui-${{ runner.os }}-yarn-

      # - name: Build debezium-checkstyle
      #   run: mvn clean install -f debezium/pom.xml -pl support/checkstyle -DskipTests -DskipITs

      # - name: Test Debezium UI
      #   run: mvn clean install -f dbzui -B -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      
      # - name: Build the stack
      #   run: docker-compose -f dbzui/docker-compose.yml up -d 
  test:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - name: Checkout Debezium UI
        uses: actions/checkout@v2
        with:
          repository: uidoyen/debtest
          path: dbzui
          
      - name: Run E2E test
        run: cypress run --project ./dbzui/ui/packages/ui/